crm/src/main/java/cn/gson/crm/controller/beforesale/CareCusController.java
package cn.gson.crm.controller.beforesale;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.alibaba.fastjson.JSONObject;

import cn.gson.crm.model.dao.CustomerDao;
import cn.gson.crm.model.dao.EmployeeDao;
import cn.gson.crm.model.dao.CareCusDao;
import cn.gson.crm.model.entity.CareCustomer;
import cn.gson.crm.model.entity.Customer;
import cn.gson.crm.model.entity.Employee;
import cn.gson.crm.model.mapper.CustomerMapper;

@Controller
@RequestMapping("/carecus")
public class CareCusController {

	@Autowired
	CareCusDao carecusDao;
	
	@Autowired
	CustomerMapper cusMapper;
	
	@Autowired
	CustomerDao cusDao;
	
	@Autowired
	EmployeeDao empDao;
	
	@RequestMapping
	public String init() {
		return "beforesale/carecus/carecus";
	}
	
	@RequestMapping("list")
	@ResponseBody
	public Map<String, Object> list(@RequestParam(defaultValue = "1") int page,
			@RequestParam(defaultValue = "10") int rows,
			HttpServletRequest req
			){
		Employee emp = (Employee) req.getSession().getAttribute("employee");
		PageRequest pr = new PageRequest(page - 1, rows,new Sort(Direction.DESC,"id"));
		Page<CareCustomer> carecus = null;
		//销售员显示所有与当前登录用户相关且未删除的客户线索
		if (emp.getRole().getRoleName().equals("销售员")) {
			carecus = carecusDao.findAllByEmployeeAndIsDelete(emp,false,pr);
		}else {
			//管理者显示所有未删除的客户关怀线索
			carecus = carecusDao.findAllByIsDelete(false, pr);
		}
		Map<String, Object> data = new HashMap<>();
		data.put("rows", carecus.getContent());
		data.put("total", carecus.getTotalElements());
		return data;
	}
	
	/**
	 * 根据是否有Id判断是编辑还是新建
	 * @param id
	 * @param model
	 * @return
	 */
	@RequestMapping({"carecusform","carecusform/{id}"})
	public String cusForm(@PathVariable(required=false) Long id,Model model){
		//如果是编辑，则将信息赋到页面去
		if (id != null) {
			model.addAttribute("c",carecusDao.findOne(id));
		}
		return "beforesale/carecus/carecusform";
	}
	
	
	/**
	 * 保存客户关怀记录
	 * @param carecus
	 * @param contacts
	 * @param br
	 * @return
	 */
	@RequestMapping("/save")
	@ResponseBody
	@Transactional
	public JSONObject save(@Valid CareCustomer carecus,
			@Valid Long cusid,
			HttpSession session,
			BindingResult br) {
		JSONObject result = new JSONObject();
		if (br.hasErrors()) {
			result.put("err", "校验失败！");
		}else {
			//客户外键
			Customer cus = cusDao.findOne(cusid);
			//员工外键(这里是临时这么用，登录以后可以使用session里读取出来使用)
			Employee emp = (Employee)session.getAttribute("employee");
			if (cus == null) {
				result.put("err", "没有此联系人。");
			}else {
				carecus.setCustomer(cus);
				carecus.setEmployee(emp);
				carecusDao.save(carecus);
				result.put("success", true);
			}	
		}
		return result;
	}
	
	
	/**
	 * 数据库并没有删除，只是更改了删除状态这个字段，使其不显示
	 * @param id
	 * @return
	 */
	@GetMapping("delete/{id}")
	@ResponseBody
	public Map<String, Object> delete(@PathVariable Long id){
		Map<String, Object> data = new HashMap<>();
		
		try {
			CareCustomer carecus = carecusDao.findOne(id);
			carecus.setDelete(true);
			carecusDao.save(carecus);
			data.put("success", true);
		} catch (Exception e) {
			e.printStackTrace();
			data.put("success", false);
			data.put("errorMsg", e.getMessage());
		}
		return data;
	}
	
	/**
	 * 根据id和姓名查询联系人
	 * @param seacont
	 * @return
	 */
	@PostMapping("search/{seacont}")
	@ResponseBody
	public List<Customer> search(@PathVariable String seacont,Model model){

		List<Customer> cus = new ArrayList<>();
		cus = cusMapper.searchCon(seacont);
		return cus;
	}
}

crm/src/main/java/cn/gson/crm/controller/beforesale/OpportunityController.java
package cn.gson.crm.controller.beforesale;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;

import cn.gson.crm.model.dao.CustomerDao;
import cn.gson.crm.model.dao.EmployeeDao;
import cn.gson.crm.model.dao.OpportunityDao;
import cn.gson.crm.model.entity.Customer;
import cn.gson.crm.model.entity.Employee;
import cn.gson.crm.model.entity.SalesOpportunity;
import cn.gson.crm.model.mapper.OpportunityMapper;

/**
 * 机会列表 查询所有销售机会主题 根据客户id查询所有销售机会主题
 * 
 * @author PD
 *
 */
@Controller
@RequestMapping("opp")
public class OpportunityController {
	@Autowired
	OpportunityDao opdao;

	@Autowired
	CustomerDao cusdao;
	
	@Autowired
	EmployeeDao empDao;
	
	@Autowired
	OpportunityMapper oppmapper;

	@RequestMapping
	public String opp() {
		return "beforesale/opportunity";
	}

	// 加载机会列表中的表格
	@RequestMapping("oppform")
	@ResponseBody
	public Map<String, Object> form(@RequestParam(defaultValue = "1") int page,
			@RequestParam(defaultValue = "2") int rows,
			HttpSession session) {
		Employee emp = (Employee) session.getAttribute("employee");
		PageRequest pr = new PageRequest(page - 1, rows, new Sort(Direction.ASC, "id"));
		Map<String, Object> data = new HashMap<>();
		//销售主管登录，能查看到所有员工的客户的销售机会,销售员登录，只能看到自己手下的客户的销售机会
		if(emp.getRole().getRoleName().equals("销售员")){
		PageHelper.startPage(page,rows,true);
		List<SalesOpportunity> sp = oppmapper.selectOppByemp(emp.getId());
		PageInfo<SalesOpportunity> pageinfo = new PageInfo<>(sp);
			data.put("rows", pageinfo.getList());
			data.put("total", pageinfo.getTotal());
		}else{
			//查询所有
			System.out.println(emp.toString());
			Page<SalesOpportunity> sp = opdao.findAllByIsDelete(false, pr);
			data.put("rows", sp.getContent());
			data.put("total", sp.getTotalElements());
		}
		return data;
	}

	/**
	 * 加载机会列表中的新增、编辑表格
	 * 
	 * @author PD
	 * @return
	 */
	@RequestMapping({ "oppaddform/{id}", "oppaddform" })
	public String edit(@PathVariable(required = false) Long id, Model model) {
		if (id != null) {
			model.addAttribute("r", opdao.findOne(id));
		}
		return "beforesale/opportunity/oppaddform";
	}

	@GetMapping("saveedit")
	@ResponseBody
	public JSONObject saveedit(@RequestParam(value="id") Long id,
			@RequestParam(value="updateTime") String updateTime,
			@RequestParam(value="expectedTime") String expectedTime,
			@RequestParam(value="topic") String topic,
			@RequestParam(value="customerid") Long customerid,
			@RequestParam(value="stage") String stage,@RequestParam(value="priority") int priority,
			@RequestParam(value="possibility") String possibility,@RequestParam(value="expectedMoney") double expectedMoney) {
			JSONObject result = new JSONObject();
			SalesOpportunity opp = opdao.findOne(id);	
			opp.setCustomer(cusdao.findOne(customerid));
			opp.setExpectedMoney(expectedMoney);
			opp.setPossibility(possibility);
			opp.setPriority(priority);
			opp.setStage(stage);
			opp.setTopic(topic);
			SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
			SimpleDateFormat formatter1 = new SimpleDateFormat("yyMMdd");
			//转换时间
			Date date = null;
			Date date1=null;
			try {
				date = formatter.parse(updateTime);
				date1 = formatter.parse(expectedTime);
			} catch (ParseException e) {
				// TODO Auto-generated catch block
				System.out.println("日期转换异常！");
			}
			opp.setUpdateTime(date);
			opp.setExpectedTime(date1);
			
			if(opdao.save(opp) != null){
				result.put("message", "保存成功！");
			}else{
				result.put("message", "保存失败！");
			}
		
		return result;
	}
	
	@GetMapping("savenew")
	@ResponseBody
	public JSONObject savenew(
			@RequestParam(value="updateTime") String updateTime,
			@RequestParam(value="expectedTime") String expectedTime,
			@RequestParam(value="topic") String topic,
			@RequestParam(value="customerid") Long customerid,
			@RequestParam(value="stage") String stage,@RequestParam(value="priority") int priority,
			@RequestParam(value="possibility") String possibility,@RequestParam(value="expectedMoney") double expectedMoney) {
			JSONObject result = new JSONObject();
			SalesOpportunity opp = new SalesOpportunity();
			opp.setCustomer(cusdao.findOne(customerid));
			opp.setExpectedMoney(expectedMoney);
			opp.setPossibility(possibility);
			opp.setPriority(priority);
			opp.setStage(stage);
			opp.setTopic(topic);
			SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
			SimpleDateFormat formatter1 = new SimpleDateFormat("yyMMdd");
			//转换时间
			Date date = null;
			Date date1=null;
			try {
				date = formatter.parse(updateTime);
				date1 = formatter.parse(expectedTime);
			} catch (ParseException e) {
				// TODO Auto-generated catch block
				System.out.println("日期转换异常！");
			}
			opp.setUpdateTime(date);
			opp.setExpectedTime(date1);
			
			if(opdao.save(opp) != null){
				result.put("message", "保存成功！");
			}else{
				result.put("message", "保存失败！");
			}
		return result;

	}
	
	
	
	/**
	 * 批量删除
	 */
	@PostMapping("delete/{id}")
	@Transactional
	@ResponseBody
	public JSONObject delete(@PathVariable Long[] id) {
		JSONObject result = new JSONObject();
		try {
			// 遍历id数组，先查询所有需要进行操作的对象
			for (int i = 0; i < id.length; i++) {
				SalesOpportunity sps = opdao.findOne(id[i]);
				sps.setDelete(true);
				opdao.save(sps);
			}
			result.put("success", true);
		} catch (Exception e) {
			result.put("errorMsg", e.getStackTrace());
		}
		return result;
	}

	/**
	 * @author PD 加载解决方案表格每一个解决方案的详细信息
	 * @return
	 */
	@RequestMapping("oppdetailsform/{id}")
	public String solutiondetailsform(@PathVariable(required = false) Long id, Model model) {

		return "beforesale/opportunity/oppdetailsform";
	}

	/**
	 * 图表数据
	 * 
	 * @author PD
	 * @return
	 */
	// @RequestMapping("oppdata")
	// @ResponseBody
	// public JSONArray getdata(Model model){
	// JSONArray jsonArray = new JSONArray();
	// List<SalesOpportunity> opplist = opdao.findAllByIsDelete(false);
	// for (SalesOpportunity opp : opplist) {
	// JSONObject jsonObject = new JSONObject();
	// jsonObject.put("money", opp.getExpectedMoney());
	// jsonObject.put("priority",opp.getPriority());
	// jsonArray.add(jsonObject);
	// // model.addAttribute("jsonArray", jsonArray);
	// }
	// return jsonArray;
	// }

	/**
	 * 查询所有销售机会主题
	 * 
	 * @author hzl
	 * @return
	 */
	@RequestMapping("opportunitylist")
	@ResponseBody
	public JSONArray getCustomer() {
		JSONArray jsonArray = new JSONArray();
		List<SalesOpportunity> opportunitylist = (List<SalesOpportunity>) opdao.findAll();
		if (opportunitylist.size() > 0) {
			for (SalesOpportunity opportunity : opportunitylist) {
				jsonArray.add(opportunity);
			}
		} else {
			JSONObject jsonObj = new JSONObject();
			jsonObj.put("id", null);
			jsonObj.put("topic", "没有相应的记录");
			jsonArray.add(jsonObj);
		}
		return jsonArray;
	}

	
	/**
	 * 根据客户id查询所有销售机会主题
	 * 
	 * @author hzl
	 * @return
	 */
	@RequestMapping("getOppByCus")
	@ResponseBody
	public JSONArray getOppByCus(@RequestParam("customerid") Long cid) {
		JSONArray jsonArray = new JSONArray();
		List<SalesOpportunity> opportunitylist = opdao.findByCustomer(cusdao.findOne(cid));
		if(opportunitylist.size()>0){
			for (SalesOpportunity opportunity : opportunitylist) {
				jsonArray.add(opportunity);
			}
		}else{
			JSONObject jsonObj=new JSONObject();
			jsonObj.put("id", null);
			jsonObj.put("topic", "没有相应的记录");
			jsonArray.add(jsonObj);
		}
		return jsonArray;
	}
	

	
	/**
	 * 新增竞争对手时，跟据当前登录的用户显示不同的销售机会
	 * @return
	 */
	@RequestMapping("getOppByEmp")
	@ResponseBody
	public JSONArray getOppByEmp(HttpSession session) {
		JSONArray result = new JSONArray();
		//从session里获取当前登录用户
		Employee emp = (Employee)session.getAttribute("employee");
		//判断当前登录用户的角色
		//如果是管理员则显示所有，如果是普通销售人员就只显示他自己的
		List<SalesOpportunity> opps = null;
		if (emp.getRole().getRoleName().equals("销售员")) {
			Long empid = emp.getId();
			opps = opdao.findByEmp(empid);
			if (opps.size() > 0) {
				for (SalesOpportunity salesOpportunity : opps) {
					result.add(salesOpportunity);
				}
			}else {
				JSONObject jo = new JSONObject();
				jo.put("id", null);
				jo.put("value", "没有相应的记录");
				result.add(jo);
			}
		}else {
			opps = opdao.findAllByIsDelete(false);
			if (opps.size() > 0) {
				for (SalesOpportunity salesOpportunity : opps) {
					result.add(salesOpportunity);
				}
			}else {
				JSONObject jo = new JSONObject();
				jo.put("id", null);
				jo.put("value", "没有相应的记录");
				result.add(jo);
			}
		}
		return result;
	}

	/**
	 * //根据角色查询销售机会

crm/src/main/webapp/WEB-INF/jsp/beforesale/opportunity/oppaddform.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<form id="oppaddForm" method="post" style="margin: 0; padding: 10px">
	<input type="hidden" name="id" value="${r.id }" />
	<input type="hidden" id="priority" value="${r.priority}" />
	<div
		style="height: 70px; border-bottom: 1px solid black; line-height: 50px">
		<span style="font-size: 20px">销售机会</span>
	</div>
	<div style="height: 140px; margin-top: 35px">
		<div style="height: 20px; text-align: center">
			<span
				style="background-color: #EBEFF2 !important; font-weight: bold; width: 30px">机会</span><br />
		</div>
		<div style="height: 120px">
			<table>
				<tr>
					<td>
						<div style="width: 370px; height: 60px; margin-left: 10px">
							<input name="topic" class="easyui-textbox" label="机会主题"
								style="width: 300px; height: 40px" value="${r.topic }" />
						</div>

					</td>

					<td>
						<div style="width: 370px; height: 60px; margin-left: 10px">

							<input name="updateTime" class="easyui-datebox" label="更新时间"
								style="width: 300px; height: 40px" value="${r.updateTime }" />

						</div>

					</td>
				</tr>
				<tr>
					<!-- 只能给自己手下的客户添加销售机会，如果是客户视图界面则不能修改客户 -->
					<td>
						<div style="width: 370px; height: 60px; margin-left: 10px">
						<input id="opp1" class="easyui-combobox" label="客户"
						style="width: 300px; height: 40px" value="${r.customer.name }"
						data-options="url:'cus/allcustomerlist',valueField:'id',
    					textField:'name'">
    					<input id="opp2" type="hidden" name="customer.id" value="${r.customer.id }"/>
    					<script type="text/javascript">
    					$('#opp1').combobox({
    						onSelect : function(record) {
    							$("#opp2").val(record.id);
    						}
    					});
    					</script>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<!-- 基本情况 -->

	<div style="height: 140px; margin-top: 40px">
		<div style="height: 20px; text-align: center">
			<span
				style="background-color: #EBEFF2 !important; font-weight: bold; width: 30px">基本情况</span><br />
		</div>
		<div style="height: 120px">
			<table>
				<tr>
					<td>
						<div style="width: 330px; height: 60px; margin-left: 10px">

							<select id="jieduan" name="stage" class="easyui-combobox"
								style="width: 300px; height: 40px" value="${r.stage}"
								 label="阶段">
								<option value="初期沟通"<c:if test="${r.stage == '初期沟通'}">selected</c:if>>初期沟通</option>
								<option value="立项评估"<c:if test="${r.stage == '立项评估'}">selected</c:if>>立项评估</option>
								<option value="需求分析"<c:if test="${r.stage == '需求分析'}">selected</c:if>>需求分析</option>
								<option value="方案制定"<c:if test="${r.stage == '方案制定'}">selected</c:if>>方案制定</option>
								<option value="招投标/竞争"<c:if test="${r.stage == '招投标/竞争'}">selected</c:if>>招投标/竞争</option>
								<option value="商务谈判"<c:if test="${r.stage == '商务谈判'}">selected</c:if>>商务谈判</option>
								<option value="合同签约"<c:if test="${r.stage == '合同签约'}">selected</c:if>>合同签约</option>
							</select>

						</div>

					</td>
					<td>
						<div style="width: 370px; height: 60px; margin-left: 60px">
							<select id= "xiaoshou" name="priority" class="easyui-combobox"
								style="width: 300px; height: 40px"
								label="销售优先级" value="${r.priority }">
								<option value="1">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
								<option value="4">4</option>
							</select>
						</div>
					</td>
				</tr>
			</table>
		</div>

	</div>

	<!-- 预期 -->

	<div style="height: 140px; margin-top: 20px">
		<div style="height: 20px; text-align: center">
			<span
				style="background-color: #EBEFF2 !important; font-weight: bold; width: 30px">预期效果</span><br />
		</div>
		<div style="height: 120px">
			<table>
				<tr>
					<td>
						<div style="width: 370px; height: 60px; margin-left: 10px">
							<input name="expectedTime" class="easyui-datebox" label="签约时间"
								style="width: 300px; height: 40px" value="${r.expectedTime }" />

						</div>

					</td>

					<td>
						<div style="width: 370px; height: 60px; margin-left: 10px">

							<input name="possibility" class="easyui-textbox" label="可能性"
								style="width: 300px; height: 40px" value="${r.possibility }">

						</div>

					</td>
				</tr>

				<tr>
					<td colspan="2">
						<div style="width: 370px; height: 60px; margin-left: 10px">
							<input name="expectedMoney" class="easyui-textbox" label="签约金额"
								style="width: 300px; height: 40px" " value="${r.expectedMoney }">
						</div>
					</td>

				</tr>

			</table>
		</div>

	</div>
</form>

<script type="text/javascript">

$(function(){
	//销售优先级
	 var priority = $("#priority").val();
	
	 if(priority==1){
		 $("#xiaoshou option[value='1']").attr("selected","selected");
	 }if(priority==2){
		 $("#xiaoshou option[value='2']").attr("selected","selected");
	 }if(priority==3){
		 $("#xiaoshou option[value='3']").attr("selected","selected");
	 }if(priority==4){
		 $("#xiaoshou option[value='4']").attr("selected","selected");
	 }

	
});
</script>




crm/src/main/webapp/WEB-INF/jsp/beforesale/opportunity/oppdetailsform.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

    
<form id="oppdetailsform" method="post"
	style="margin: 0; padding: 10px 30px">
	<input type="hidden" name="id" >
		<table style="margin-top:30px">

		<tr>
			<td>
				<div style="margin-bottom: 30px">
					<span>方案主题</span>
				</div>
				
			</td>
				
			<td>
				<div style="margin-bottom: 30px">
					<span>〖楼宇对讲和防盗报警〗</span>
					</div>
			</td>
		
			
		</tr>


		<tr>
			<td><div style="margin-bottom: 30px">
					<span>方案主题</span>
				</div></td>
			<td>
				<div style="margin-bottom: 30px">
					<span>〖楼宇对讲和防盗报警〗</span>
				</div>
			</td>
		</tr>

		<tr>
		
		<tr>
		
			<td>
				<div style="margin-bottom: 40px">
					<span>方案主题</span>
				</div>
			</td>
			
			<td><div style="margin-bottom: 40px;margin-left:10px">
					<span>可靠的上报管理中心，不能出现误报、尤其是漏报状况，确保报警成功。</span>
			</div></td>
			
			
		</tr>
		

		<tr>
		
			<td>
				<div style="margin-bottom: 40px">
					<span>方案主题</span>
				</div>
			</td>
			
			<td><div style="margin-bottom: 40px;margin-left:10px">
					<span>可靠的上报管理中心，不能出现误报、尤其是漏报状况，确保报警成功。</span>
			</div></td>
			
			
		</tr>
		
		<tr>
		
			<td>
				<div style="margin-bottom: 40px;margin-left:10px">
					<span>方案主题</span>
				</div>
			</td>
			
			<td><div style="margin-bottom: 40px;margin-left:10px">
					<span>可靠的上报管理中心，不能出现误报、尤其是漏报状况，确保报警成功。</span>
			</div></td>
			
			
		</tr>

	</table>


</form>